### ISSUE TITLE
What does it exactly do?

### ISSUE THREAD

**Issue by MANTENN** [NickCis/micronize#1]
What is the fn parameter?

**Comment by NickCis** [comment]
The idea of this package was just to allow you to use micro in a programmatic way (e.g.: using it in aws lambda or a plain http server).

Currently [Micro](https://github.com/zeit/micro#programmatic-use) provides a programmatic use, so, this package can be though of something useless.

If you compare how the main [micro's exported function is developed](https://github.com/zeit/micro/blob/master/packages/micro/lib/index.js#L25) you'll find that is very similar to [this package implementation](https://github.com/NickCis/micronize/blob/master/index.js).
